// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fkijyjggrvggzehhzjlq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZraWp5amdncnZnZ3plaGh6amxxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM1NTQzMzMsImV4cCI6MjA2OTEzMDMzM30.z0iCTcZ81dim5XYB2H_eSthlqqm2pzlXq7emdsKIRxY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});